# This triggers on all merged PRs into main

name: Main - TF Apply

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  dev:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[DEV]"
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-run.yml@main
    with:
      environment: 'dev'
      region: 'eu-central-1'
      working-directory: '.'
      action: 'apply'
    secrets: inherit
